osx_image: beta-xcode6.2
sudo: false
language: objective-c
install:
- gem install cocoapods
before_script:
- export HOME=`pwd`
- export TIMESTAMP=`date`
- mkdir -p .git
- git config --global credential.helper "store --file=$HOME/.git/credentials"
- git config --global user.email "carlos@adaptive.me"
- git config --global user.name "carloslozano"
- git config --global push.default simple
- echo "https://${GH_TOKEN}:@github.com" > $HOME/.git/credentials
- git remote set-url origin https://github.com/AdaptiveMe/adaptive-arp-api-lib-darwin.git
- export GIT_TAG=`git describe --tags --abbrev=0`
script:
- pod lib lint --quick
after_success: |-
  if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then  
    echo "Publish to Cocoapods..."   
    echo $PORK_MODE1 > $HOME/.netrc
    echo $PORK_MODE2 >> $HOME/.netrc
    echo $PORK_MODE3 >> $HOME/.netrc
    chmod 0600 $HOME/.netrc 
    pod trunk push AdaptiveArpApi.podspec
  elif [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    export SOURCE_HOME=`pwd`
    mkdir -p temp
    cd temp
    git clone https://github.com/AdaptiveMe/adaptive-arp-api.git
    cd adaptive-arp-api
    export API_TAG=`git describe --abbrev=0`
    export API_TAG=`echo ${API_TAG//[v]/ }`
    rm -Rf $SOURCE_HOME/temp  
    cd $SOURCE_HOME   
    export POD_TAG=`node ./version.js`
    echo Git: $GIT_TAG Pod: $POD_TAG Api: $API_TAG
    if [ "$GIT_TAG" == "$POD_TAG" -a "$GIT_TAG" != "$API_TAG" ]; then
        echo "Bump version here to ${API_TAG}"
        #git checkout master
        #git pull -v
        npm install -g podspec-bump
        
        mkdir -p temp
        cd temp
        git clone https://github.com/AdaptiveMe/adaptive-arp-api-lib-darwin.git
        cd adaptive-arp-api-lib-darwin
        podspec-bump -i $API_TAG -w      
        git add -A .
        git status
        git commit -v -m "API Specification ${API_TAG} at ${TIMESTAMP}."
        git status
        git --version
        git push -v origin
    elif [ "$GIT_TAG" != "$POD_TAG" -a "$GIT_TAG" != "$API_TAG" ]; then
        echo "Drop tag to ${API_TAG}"
        git tag -a "${API_TAG}" -m "API Specification ${API_TAG}"
        git push origin HEAD:master --tags
    fi
  fi
after_failure:
- echo "Having a bad moment..."
env:
  global:
    secure: QFnB+ezMMh5uJAvqOba1CbGVOK1AjOBmUje+GBXHxa5KBaGQ37VX3D9V8QLCEZf/9b50h2URH3XuTlQ4TUAQoMBEfU/SFIvKemc+lgwIBd+lDVbceKuhLxl3c0ugEfwMGwlqdl0BNeA95/2ofX86EVKrUO0TLxa2CLM7l3UdIDo=
